blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/dev-taherm/my-profile-oc#readme
    about: Check the README for setup instructions and documentation
  - name: Discussions
    url: https://github.com/dev-taherm/my-profile-oc/discussions
    about: Ask questions and discuss ideas
